### ISSUE TITLE
Handle rgInstall.getExecutable() null value

### ISSUE THREAD

**Issue by rvansa** [vjuranek/radargun-plugin#10]
I got NPE in NodeRunner.call() when starting the process as one of the args on command line is null.

Moreover, you should count down the latch in finally block, otherwise the job is stuck waiting for the node to finish, though the runner has already crashed.

**Comment by vjuranek** [comment]
Fixed in d43b46d88e71a1f9e88cfe228eabb9dc392c89ff

I'm not sure how can I handle situation when there's some issue with resolving RG executables, so throwing `AbortException` which should abort the build - probably nothing better can be done here.
