### ISSUE TITLE
YAML file produces bad command line for RadarGun Slaves

### ISSUE THREAD

**Issue by alanfx** [vjuranek/radargun-plugin#28]
The following YAML file:
>---
>defaultsEnv: &defaultsEnv
>    JAVA_HOME: "/home/field11/builds/jdk1.8.0_45/"
>
>defaultsJava: &defaultsJava
>    java.net.preferIPv4Stack: "true"
>    resolve.dns: "false"
>
>defaultsJvmOpts: &defaultsJvmOpts
>  jvmOpts: "-server -Xms10g -Xmx10g -XX:+UseLargePages"
>
>defaultsMasterJvmOpts: &defaultsMasterJvmOpts
>  jvmOpts: "-server -Xms8g -Xmx8g -XX:+UseLargePages"
>
>nodes:
>-
>  apex730:
>    <<: *defaultsMasterJvmOpts
>    javaProps:
>      <<: *defaultsJava
>    envVars:
>      <<: *defaultsEnv
>-
>  apex731:
>    <<: *defaultsJvmOpts
>    javaProps:
>      jgroups.tcp.address: 192.168.117.12
>      jgroups.tcp.port: "7800"
>      jgroups.udp.bind_addr: 192.168.117.12
>      jgroups.mcast.addr: 234.9.55.146
>      jgroups.udp.mcast_port: "52000"
>      site.servers.tcp: 192.168.117.12:7800;192.168.117.13:7800;
>      site.servers.udp: 192.168.117.12:52000;192.168.117.13:52000;
>      site.servers.hotrod: 192.168.117.12:11222;192.168.117.13:11222;
>      site.clients.tcp: 192.168.117.14:7800;
>      site.clients.udp: 192.168.117.14:52000;
>      site.clients.hotrod: 192.168.117.14:11222;
>      site.default_site.tcp: 192.168.117.12:7800;192.168.117.13:7800; 192.168.117.14:7800;
>      site.default_site.udp: 192.168.117.12:52000;192.168.117.13:52000; 192.168.117.14:52000;
>      site.default_site.hotrod: 192.168.117.12:11222;192.168.117.13:11222; 192.168.117.14:11222;
>      <<: *defaultsJava
>    envVars:
>      <<: *defaultsEnv

Produces this command lines for a slave node:
`+ mrsh apex731 cd '/home/field11/jenkins/home/jobs/test-rg-plugin/workspace;' env 'JAVA_HOME="/home/field11/builds/jdk1.8.0_45/"' /bin/sh /home/field11/builds/RadarGun-2.1.0-SNAPSHOT/bin/slave.sh -m apex730 -t -w -J ''\''-server' -Xms10g -Xmx10g -XX:+UseLargePages -Djava.net.preferIPv4Stack=true -Dresolve.dns=false '-Dsite.default_site.hotrod=192.168.117.12:11222;192.168.117.13:11222;' '192.168.117.14:11222;' '-Dsite.default_site.udp=192.168.117.12:52000;192.168.117.13:52000;' '192.168.117.14:52000;' '-Dsite.default_site.tcp=192.168.117.12:7800;192.168.117.13:7800;' '192.168.117.14:7800;' '-Dsite.clients.hotrod=192.168.117.14:11222;' '-Dsite.clients.udp=192.168.117.14:52000;' '-Dsite.clients.tcp=192.168.117.14:7800;' '-Dsite.servers.hotrod=192.168.117.12:11222;192.168.117.13:11222;' '-Dsite.servers.udp=192.168.117.12:52000;192.168.117.13:52000;' '-Dsite.servers.tcp=192.168.117.12:7800;192.168.117.13:7800;' -Djgroups.udp.mcast_port=52000 -Djgroups.mcast.addr=234.9.55.146 -Djgroups.udp.bind_addr=192.168.117.12 -Djgroups.tcp.port=7800 -Djgroups.tcp.address=192.168.117.12 ''\''' -i 0`

Notice the '192.168.117.14:11222;', '192.168.117.14:7800;', and '192.168.117.14:52000;' arguments passed on the command line that cause the node to fail to start.

**Comment by vjuranek** [comment]
Hi @alanfx ,
did you add any additional quotes in the script or here? I added couple of unit test for this use case and also tried to reproduce locally with exactly this YAML config, and still cannot reproduce. 

On my localhost I'm getting command bellow, which seems to me correct (not 100% as it does nothing, just prints cmd to be executed):

```
ssh apex731 cd  /plugins/radargun-plugin/work/workspace/issue28; env  JAVA_HOME="/home/field11/builds/jdk1.8.0_45/"  /bin/sh /tmp/radarun/RadarGun-2.1.0-SNAPSHOT/bin/slave.sh -m apex730 -t -w --add-plugin plugin-path --add-config plugin:config-path -J  '-server -Xms10g -Xmx10g -XX:+UseLargePages -Djava.net.preferIPv4Stack=true -Dresolve.dns=false -Dsite.default_site.hotrod=192.168.117.12:11222;192.168.117.13:11222; 192.168.117.14:11222; -Dsite.default_site.udp=192.168.117.12:52000;192.168.117.13:52000; 192.168.117.14:52000; -Dsite.default_site.tcp=192.168.117.12:7800;192.168.117.13:7800; 192.168.117.14:7800; -Dsite.clients.hotrod=192.168.117.14:11222; -Dsite.clients.udp=192.168.117.14:52000; -Dsite.clients.tcp=192.168.117.14:7800; -Dsite.servers.hotrod=192.168.117.12:11222;192.168.117.13:11222; -Dsite.servers.udp=192.168.117.12:52000;192.168.117.13:52000; -Dsite.servers.tcp=192.168.117.12:7800;192.168.117.13:7800; -Djgroups.udp.mcast_port=52000 -Djgroups.mcast.addr=234.9.55.146 -Djgroups.udp.bind_addr=192.168.117.12 -Djgroups.tcp.port=7800 -Djgroups.tcp.address=192.168.117.12 ' -i 0
```

**Comment by alanfx** [comment]
Hey @vjuranek,

Your command also has the issue. " -Dsite.default_site.hotrod=192.168.117.12:11222;192.168.117.13:11222; 192.168.117.14:11222;". There is the site.default_site.hotrod property, then a space and "192.168.117.14:11222;" with no property name or equal sign.

**Comment by vjuranek** [comment]
I see, thanks @alanfx ! I thought that there's some issue with quotes and didn't notices the space...

**Comment by vjuranek** [comment]
@alanfx isn't the root of the issue that you have a space in your config file?
`site.default_site.hotrod: 192.168.117.12:11222;192.168.117.13:11222; 192.168.117.14:11222;`

**Comment by alanfx** [comment]
@vjuranek, I think you are right! I didn't notice that space in the site.default_site.* properties, but I'll fix my bash script and verify that is the root cause. Thanks!

**Comment by alanfx** [comment]
Closing this, since it was user error!
