### ISSUE TITLE
Workaround for truncated logs

### ISSUE THREAD

**Issue by vjuranek** [vjuranek/radargun-plugin#31]
RG3 restarts whole JVM after each stage, which broke `-t` option, see [RG #314](https://github.com/radargun/radargun/issues/314). Plugin uses this feature for capturing the logs and thus logs are truncated. Try to figure out some workaround (or fix for RG :smile:  )

**Comment by vjuranek** [comment]
Archiving all `stdout_*` logs should be a sufficient workaround

**Comment by alanfx** [comment]
The issue is archiving only the `stdout_slave_*` for the running job. I'm not sure how to do that in the job configuration...

**Comment by vjuranek** [comment]
the issue was solved directly in RG, closing this one.
