### ISSUE TITLE
Remove deprecation from JVM option

### ISSUE THREAD

**Issue by vjuranek** [vjuranek/radargun-plugin#52]
It's useful for setting JVM option on RG master. It should be deprecated only on RG slaves, but not on the master.

**Comment by alanfx** [comment]
👍 Setting the JVM options for the master node is not a feature in RadarGun 3, and it is useful in case the reports are very large.

**Comment by vjuranek** [comment]
Fixed in `f1f96e418e9830d7b3fd6777db5137a0375a93d5`
