### ISSUE TITLE
RG master and node links same log if run on the same node

### ISSUE THREAD

**Issue by vjuranek** [vjuranek/radargun-plugin#53]
When master and node are run on the same node, log links on the left side points to the same log (master log) for master as well as for the slave.

**Comment by jmarkos** [comment]
Actually they point to the same log file, which is a a combined log of the master and slave (not just master log).

**Comment by vjuranek** [comment]
Should be fixed in ddcbbce5d2629caf3ac8c1eb56c59f59e91dd2c2
